name: CI

on:
  push:
    tags:
      - '*'
  release:
    types: [created]

jobs:
  build:
    name: "Build and Release"
    runs-on: ubuntu-latest
    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports:
        - 8000:8000
    steps:
      - uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v9
      - name: Install Dependencies
        run: |
          poetry env use python3
          source $(poetry env info --path)/bin/activate
          poetry install
      - name: Run tests
        run: |
          pytest
          pytest --cov .
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 18
      - name: Install serverless
        run: npm install -g serverless serverless-python-requirements
      - name: Deploy Production
        if: startsWith(github.ref, 'refs/tags/')
        run: serverless deploy -s prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
